// Code generated by protoc-gen-go.
// source: widevine_pssh_data.proto
// DO NOT EDIT!

/*
Package widevine_pssh_data is a generated protocol buffer package.

It is generated from these files:
	widevine_pssh_data.proto

It has these top-level messages:
	WidevinePsshData
*/
package widevine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type WidevinePsshData_Algorithm int32

const (
	WidevinePsshData_UNENCRYPTED WidevinePsshData_Algorithm = 0
	WidevinePsshData_AESCTR      WidevinePsshData_Algorithm = 1
)

var WidevinePsshData_Algorithm_name = map[int32]string{
	0: "UNENCRYPTED",
	1: "AESCTR",
}
var WidevinePsshData_Algorithm_value = map[string]int32{
	"UNENCRYPTED": 0,
	"AESCTR":      1,
}

func (x WidevinePsshData_Algorithm) Enum() *WidevinePsshData_Algorithm {
	p := new(WidevinePsshData_Algorithm)
	*p = x
	return p
}
func (x WidevinePsshData_Algorithm) String() string {
	return proto.EnumName(WidevinePsshData_Algorithm_name, int32(x))
}
func (x *WidevinePsshData_Algorithm) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WidevinePsshData_Algorithm_value, data, "WidevinePsshData_Algorithm")
	if err != nil {
		return err
	}
	*x = WidevinePsshData_Algorithm(value)
	return nil
}
func (WidevinePsshData_Algorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type WidevinePsshData struct {
	Algorithm *WidevinePsshData_Algorithm `protobuf:"varint,1,opt,name=algorithm,enum=WidevinePsshData_Algorithm" json:"algorithm,omitempty"`
	KeyId     [][]byte                    `protobuf:"bytes,2,rep,name=key_id" json:"key_id,omitempty"`
	// Content provider name.
	Provider *string `protobuf:"bytes,3,opt,name=provider" json:"provider,omitempty"`
	// A content identifier, specified by content provider.
	ContentId []byte `protobuf:"bytes,4,opt,name=content_id" json:"content_id,omitempty"`
	// The name of a registered policy to be used for this asset.
	Policy *string `protobuf:"bytes,6,opt,name=policy" json:"policy,omitempty"`
	// Crypto period index, for media using key rotation.
	CryptoPeriodIndex *uint32 `protobuf:"varint,7,opt,name=crypto_period_index" json:"crypto_period_index,omitempty"`
	// Optional protected context for group content. The grouped_license is a
	// serialized SignedMessage.
	GroupedLicense   []byte `protobuf:"bytes,8,opt,name=grouped_license" json:"grouped_license,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *WidevinePsshData) Reset()                    { *m = WidevinePsshData{} }
func (m *WidevinePsshData) String() string            { return proto.CompactTextString(m) }
func (*WidevinePsshData) ProtoMessage()               {}
func (*WidevinePsshData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WidevinePsshData) GetAlgorithm() WidevinePsshData_Algorithm {
	if m != nil && m.Algorithm != nil {
		return *m.Algorithm
	}
	return WidevinePsshData_UNENCRYPTED
}

func (m *WidevinePsshData) GetKeyId() [][]byte {
	if m != nil {
		return m.KeyId
	}
	return nil
}

func (m *WidevinePsshData) GetProvider() string {
	if m != nil && m.Provider != nil {
		return *m.Provider
	}
	return ""
}

func (m *WidevinePsshData) GetContentId() []byte {
	if m != nil {
		return m.ContentId
	}
	return nil
}

func (m *WidevinePsshData) GetPolicy() string {
	if m != nil && m.Policy != nil {
		return *m.Policy
	}
	return ""
}

func (m *WidevinePsshData) GetCryptoPeriodIndex() uint32 {
	if m != nil && m.CryptoPeriodIndex != nil {
		return *m.CryptoPeriodIndex
	}
	return 0
}

func (m *WidevinePsshData) GetGroupedLicense() []byte {
	if m != nil {
		return m.GroupedLicense
	}
	return nil
}

func init() {
	proto.RegisterType((*WidevinePsshData)(nil), "WidevinePsshData")
	proto.RegisterEnum("WidevinePsshData_Algorithm", WidevinePsshData_Algorithm_name, WidevinePsshData_Algorithm_value)
}

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x8e, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0x5d, 0x31, 0x2b, 0x3b, 0x22, 0x34, 0xf5, 0x60, 0x13, 0x2e, 0x84, 0xd3, 0x9e, 0x7a,
	0xf0, 0x0d, 0x08, 0xec, 0x95, 0x10, 0xc4, 0x18, 0x4f, 0xcd, 0x66, 0x3b, 0x81, 0x46, 0xec, 0x34,
	0xdd, 0x8a, 0xee, 0x1b, 0xfb, 0x18, 0xce, 0x1a, 0x8d, 0x09, 0xd7, 0x7e, 0xdf, 0xf7, 0x77, 0x40,
	0x7d, 0x38, 0x8b, 0x27, 0xe7, 0xd1, 0x84, 0xb6, 0x3d, 0x18, 0x5b, 0xa7, 0x5a, 0x87, 0x48, 0x89,
	0xe6, 0x5f, 0x19, 0x88, 0xe7, 0x5f, 0xb8, 0x61, 0xb6, 0x62, 0x24, 0x35, 0x14, 0xf5, 0x71, 0x4f,
	0xd1, 0xa5, 0xc3, 0x9b, 0xca, 0x66, 0x59, 0x39, 0x7e, 0x98, 0xea, 0x73, 0x4b, 0x2f, 0xfe, 0x14,
	0x39, 0x86, 0xfc, 0x15, 0x3b, 0xe3, 0xac, 0xba, 0x9c, 0x0d, 0xca, 0x91, 0x14, 0x30, 0xe4, 0xf5,
	0x13, 0x07, 0x51, 0x0d, 0x38, 0x2f, 0xa4, 0x04, 0x68, 0xc8, 0x27, 0xf4, 0xa9, 0xb7, 0xae, 0xf8,
	0x6d, 0xd4, 0x57, 0x81, 0x8e, 0xae, 0xe9, 0x54, 0xfe, 0xe3, 0x4c, 0xe1, 0xae, 0x89, 0x5d, 0x48,
	0x64, 0x02, 0x46, 0x47, 0xd6, 0x38, 0x6f, 0xf1, 0x53, 0x5d, 0x33, 0xbc, 0x95, 0xf7, 0x30, 0xd9,
	0x47, 0x7a, 0x0f, 0x68, 0x0d, 0x27, 0xe8, 0x5b, 0x54, 0xc3, 0x7e, 0x65, 0x5e, 0x42, 0xf1, 0x7f,
	0xc8, 0x04, 0x6e, 0x9e, 0xd6, 0xd5, 0x7a, 0xb9, 0x7d, 0xd9, 0xec, 0xaa, 0x95, 0xb8, 0xe0, 0x6f,
	0xf3, 0x45, 0xf5, 0xb8, 0xdc, 0x6d, 0x45, 0xf6, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x56, 0x48, 0x8b,
	0xcd, 0x05, 0x01, 0x00, 0x00,
}
